apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: kcim
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 9090

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s

        envFrom:
        - configMapRef:
            name: auth-service-config
        - secretRef:
            name: auth-service-ldap-secret

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
