apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: kcim
data:
  SPRING_PROFILES_ACTIVE: k8s

  # ===== JNDI / LDAP common =====
  LDAP_INITIALCONTEXTFACTORY: com.sun.jndi.ldap.LdapCtxFactory

  # ===== KTB LDAP =====
  LDAP_KTB_PROVIDERURL: ldap://192.168.0.59:389/o=kcs
  LDAP_KTB_SECURITYPRINCIPAL: ",ou=people,o=ktb.co.th,o=kcs"
  LDAP_KTB_MANAGER_SEARCHSCOPE: ""

  # ===== OTB LDAP =====
  LDAP_OTB_PROVIDERURL: ldap://192.168.0.59:389/o=kcs
  LDAP_OTB_SECURITYPRINCIPAL: ",ou=people,o=kcs"
  LDAP_OTB_SECURITYPRINCIPALLOGIN: ",ou=people,o=kcim2,o=kcs"
  LDAP_OTB_SECURITYPRINCIPALVERIFY: ",ou=people,o=kcim2,o=kcs"
  LDAP_OTB_MANAGER_SEARCHSCOPE: ""
  LDAP_OTB_MANAGER_PROVIDERURL: ldap://10.9.226.152:1611
  LDAP_OTB_SUFFIX: ",ou=people,o=kcim2,o=kcs"

  # ===== KTBGS LDAP =====
  LDAP_KTBGS_PROVIDERURL: ldap://192.168.0.59:389/o=kcs
  LDAP_KTBGS_SECURITYPRINCIPAL: ",ou=People,o=ktam.co.th,o=kcs"
  LDAP_KTBGS_MANAGER_SEARCHSCOPE: ""

  # ===== Active Directory =====
  AD_DOMAIN: DOMAIN.KTB.CO.TH
  AD_HOST: ldap://192.168.0.59:389
  AD_HOSTA: ldap://192.168.0.59:389
  AD_HOSTB: ldap://192.168.0.59:389
  AD_SEARCHBASE: "OU=people,OU=kcim2,OU=kcs,DC=KGS,DC=CO,DC=TH"
  USER: "kcim2adm"
  PASSWORD: "kcim2adm"

  # ===== JPA / Logging =====
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"
  LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
  LOGGING_LEVEL_COM_KTB_AUTH: DEBUG
