apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: kcim
type: Opaque
stringData:

  # LDAP
  SPRING_LDAP_USERNAME: cn=directory manager
  SPRING_LDAP_PASSWORD: password

  # Database
  SPRING_DATASOURCE_USERNAME: kcimuser
  SPRING_DATASOURCE_PASSWORD: kcimpassword
