apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: kcim
data:
  SPRING_PROFILES_ACTIVE: k8s

  SPRING_LDAP_URLS: ldap://192.168.0.59:389
  SPRING_LDAP_BASE: dc=kgs,dc=co,dc=th

  SPRING_SECURITY_LDAP_USER_SEARCH_BASE: ou=people,ou=kcim2,ou=kcs
  SPRING_SECURITY_LDAP_USER_SEARCH_FILTER: (|(uid={0})(sAMAccountName={0}))

  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_LDAP: DEBUG

 
