apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: kcim
data:
  SPRING_PROFILES_ACTIVE: k8s

  # LDAP / Active Directory
  SPRING_LDAP_URLS: ldap://192.168.0.59:389
  SPRING_LDAP_BASE: dc=kgs,dc=co,dc=th

  # Search configuration
  SPRING_LDAP_USER_SEARCH_BASE: ou=people,ou=kcim2,ou=kcs
  SPRING_LDAP_USER_SEARCH_FILTER: (sAMAccountName={0})

  # Debug LDAP (ช่วย debug login)
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_LDAP: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_LDAP: DEBUG
