apiVersion: v1
kind: Pod
metadata:
  name: kong-cm-debug
  namespace: kcim
spec:
  restartPolicy: Never
  containers:
    - name: bb
      image: busybox:1.36
      command: ["sh","-c","ls -la /etc/kong-config; echo '---'; sed -n '1,120p' /etc/kong-config/kong.yml; sleep 3600"]
      volumeMounts:
        - name: kong-api-gw-volume
          mountPath: /etc/kong-config/
  volumes:
    - name: kong-api-gw-volume
      configMap:
        name: kong-api-gw-config
        defaultMode: 420