apiVersion: v1
kind: Service
metadata:
  name: kong-api-gw
  namespace: kcim
spec:
  selector:
    app: kong-api-gw
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: admin
      port: 8001
      targetPort: 8001
    - name: status
      port: 8100
      targetPort: 8100
