apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: kcim
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://kong-api-service.kcim.svc.cluster.local:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /healthz {
        return 200 "ok";
      }
    }
